### ISSUE TITLE
Windows build failing?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/libhwloc-feedstock#16] opened 2018-10-12 18:50 UTC
Appears that recent Windows builds on `master` have been failing.

ref: https://ci.appveyor.com/project/conda-forge/libhwloc-feedstock/builds/19100526
ref: https://ci.appveyor.com/project/conda-forge/libhwloc-feedstock/builds/19019749

**Comment by jakirkham** [comment] 2018-10-12 21:51
Hmm...may be related to this ( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/17 ) then. Could just try restarting to see if it goes away then. Though if it is that issue the packages should already be uploaded.

**Comment by isuruf** [comment] 2018-10-12 22:46
Packages are uploaded. Closing as duplicate of conda-forge/conda-forge-ci-setup-feedstock#17

**Closed by isuruf** 2018-10-12 22:46 UTC
